# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LMm_gpb0C7nlg7kghzc6OT5hl-g9-7E
"""

"""
PROJECT: AI Expense Tracker (MVP)
MODULE: Expense Classifier Service
AUTHOR: AI Developer (Nguyen Ha Linh)
DATE: 2024-05-20
DESCRIPTION:
    This module trains a Naive Bayes model to categorize user expenses
    and provides an interface for the Backend to predict categories
    and check budget limits.
"""

import pandas as pd
import re
import joblib
import datetime
import json
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# ==============================================================================
# SECTION 1: CONFIGURATION & UTILITIES
# ==============================================================================

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / 'expense_classifier_model.pkl'
ENCODER_PATH = BASE_DIR / 'label_encoder.pkl'

def clean_text(text):
    """ Clean the user input before training or predicting """
    # 1. Make text lowercase
    text = str(text).lower()
    # 2. Keep only letters (a-z) and spaces. Remove numbers and symbols.
    text = re.sub(r'[^a-z\s]', '', text)
    # 3. Remove extra spaces at the beginning and end
    return text.strip()

# ==============================================================================
# SECTION 2: TRAIN AND SAVE MODEL
# ==============================================================================

def train_ai_model(csv_file = BASE_DIR / 'expense_data.csv'):
    """ Train the AI using the CSV file and save it to .pkl files """
    print("--- START TRAINING AI ---")

    # 1. Read CSV file
    try:
        df = pd.read_csv(csv_file)
        print(f"Loaded {len(df)} rows from {csv_file}")
    except FileNotFoundError:
        print(f"Error: Cannot find {csv_file}. Please upload it.")
        return

    # 2. Clean the text data
    df['clean_text'] = df['description'].apply(clean_text)

    # 3. Change Category text to numbers (Encode)
    # Example: Food -> 0, Shopping -> 1, Transport -> 2
    encoder = LabelEncoder()
    df['category_id'] = encoder.fit_transform(df['category'])
    print(f"Categories found: {list(encoder.classes_)}")

    # 4. Split data (80% for learning, 20% for testing)
    X_train, X_test, y_train, y_test = train_test_split(
        df['clean_text'], df['category_id'], test_size=0.2, random_state=42
    )

    # 5. Create and Train the Model (Naive Bayes)
    ai_model = make_pipeline(TfidfVectorizer(ngram_range=(1, 2)), MultinomialNB())
    ai_model.fit(X_train, y_train)

    # 6. Check Accuracy
    predictions = ai_model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    print(f"AI Accuracy: {accuracy * 100:.2f}%")

    # 7. Save the Brain (.pkl files) for Backend
    joblib.dump(ai_model, MODEL_PATH)
    joblib.dump(encoder, ENCODER_PATH)
    print("✅ Saved Model to .pkl files successfully!")

# ==============================================================================
# SECTION 3: PREDICT FUNCTION (FOR TESTING)
# ==============================================================================

def predict_category(text):
    """ Predict the category of a new text """
    # Load the model
    try:
        model = joblib.load(MODEL_PATH)
        encoder = joblib.load(ENCODER_PATH)
    except:
        return "Error: Cannot load model"

    # Clean text
    clean_input = clean_text(text)
    if not clean_input:
        return "Others"

    # Predict
    try:
        predict_id = model.predict([clean_input])
        category_name = encoder.inverse_transform(predict_id)[0]
        return category_name
    except:
        return "Others"

# ==============================================================================
# SECTION 4: TEST THE CODE
# ==============================================================================

if __name__ == "__main__":
    # Step 1: Train the AI (This creates the .pkl files)
    train_ai_model(BASE_DIR / 'expense_data.csv')

    # Step 2: Test the AI to see if it works
    print("\n--- TEST AI PREDICTION ---")

# List of tests (5 category)
    test_inputs = [
        "lunch with friends",       # Food
        "buying new sneakers",      # Shopping
        "parking fee 50k",          # Transport
        "notebook for class",       # Study
        "pay electricity bill"      # Others
    ]

    # Run tests and print results
    for item in test_inputs:
        result = predict_category(item)
        print(f"Input: '{item}'  ==>  Category: {result}")